[global]
address = "0.0.0.0"
port = 8080
log = "normal"

[development]
address = "0.0.0.0"
port = 8080
log = "normal"

[staging]
address = "localhost"
port = 8080
log = "normal"

[production]
address = "0.0.0.0"
port = 8080
log = "normal"